#ifndef HAS_LIGHT_AMBIENT_COLOR_CHECKER_H_
#define HAS_LIGHT_AMBIENT_COLOR_CHECKER_H_

#include "../HasValueCheckMacro.h"
HAS_VALUE_CHECK(lightAmbientColor)

#endif // !HAS_LIGHT_AMBIENT_COLOR_CHECKER_H_