#ifndef HAS_LIGHT_DIFFUSE_COLOR_CHECKER_H_
#define HAS_LIGHT_DIFFUSE_COLOR_CHECKER_H_

#include "../HasValueCheckMacro.h"
HAS_VALUE_CHECK(lightDiffuseColor)

#endif // !HAS_LIGHT_DIFFUSE_COLOR_CHECKER_H_