#ifndef HAS_MATERIAL_DIFFUSE_COLOR_CHECKER_H_
#define HAS_MATERIAL_DIFFUSE_COLOR_CHECKER_H_

#include "../HasValueCheckMacro.h"
HAS_VALUE_CHECK(materialDiffuseColor)

#endif // !HAS_MATERIAL_DIFFUSE_COLOR_CHECKER_H_