#ifndef HAS_MATERIAL_SPECULAR_COLOR_CHECKER_H_
#define HAS_MATERIAL_SPECULAR_COLOR_CHECKER_H_

#include "../HasValueCheckMacro.h"
HAS_VALUE_CHECK(materialSpecularColor)

#endif // !HAS_MATERIAL_SPECULAR_COLOR_CHECKER_H_