#ifndef HAS_MATERIAL_EMISSION_COLOR_CHECKER_H_
#define HAS_MATERIAL_EMISSION_COLOR_CHECKER_H_

#include "../HasValueCheckMacro.h"
HAS_VALUE_CHECK(materialEmissionColor)

#endif // !HAS_MATERIAL_EMISSION_COLOR_CHECKER_H_