#ifndef HAS_MATERIAL_SHININESS_CHECKER_H_
#define HAS_MATERIAL_SHININESS_CHECKER_H_

#include "../HasValueCheckMacro.h"
HAS_VALUE_CHECK(materialShininess)

#endif // !HAS_MATERIAL_SHININESS_CHECKER_H_