#ifndef KEY_BORD_KEY_TYPE_H_
#define KEY_BORD_KEY_TYPE_H_

namespace tktk
{
	enum KeybordKeyType
	{
		KEYBORD_ESCAPE          = 0x01,
		KEYBORD_1               = 0x02,
		KEYBORD_2               = 0x03,
		KEYBORD_3               = 0x04,
		KEYBORD_4               = 0x05,
		KEYBORD_5               = 0x06,
		KEYBORD_6               = 0x07,
		KEYBORD_7               = 0x08,
		KEYBORD_8               = 0x09,
		KEYBORD_9               = 0x0A,
		KEYBORD_0               = 0x0B,
		KEYBORD_MINUS           = 0x0C,    /* - on main keyboard */
		KEYBORD_EQUALS          = 0x0D,
		KEYBORD_BACK            = 0x0E,    /* backspace */
		KEYBORD_TAB             = 0x0F,
		KEYBORD_Q               = 0x10,
		KEYBORD_W               = 0x11,
		KEYBORD_E               = 0x12,
		KEYBORD_R               = 0x13,
		KEYBORD_T               = 0x14,
		KEYBORD_Y               = 0x15,
		KEYBORD_U               = 0x16,
		KEYBORD_I               = 0x17,
		KEYBORD_O               = 0x18,
		KEYBORD_P               = 0x19,
		KEYBORD_LBRACKET        = 0x1A,
		KEYBORD_RBRACKET        = 0x1B,
		KEYBORD_RETURN          = 0x1C,    /* Enter on main keyboard */
		KEYBORD_LCONTROL        = 0x1D,
		KEYBORD_A               = 0x1E,
		KEYBORD_S               = 0x1F,
		KEYBORD_D               = 0x20,
		KEYBORD_F               = 0x21,
		KEYBORD_G               = 0x22,
		KEYBORD_H               = 0x23,
		KEYBORD_J               = 0x24,
		KEYBORD_K               = 0x25,
		KEYBORD_L               = 0x26,
		KEYBORD_SEMICOLON       = 0x27,
		KEYBORD_APOSTROPHE      = 0x28,
		KEYBORD_GRAVE           = 0x29,    /* accent grave */
		KEYBORD_LSHIFT          = 0x2A,
		KEYBORD_BACKSLASH       = 0x2B,
		KEYBORD_Z               = 0x2C,
		KEYBORD_X               = 0x2D,
		KEYBORD_C               = 0x2E,
		KEYBORD_V               = 0x2F,
		KEYBORD_B               = 0x30,
		KEYBORD_N               = 0x31,
		KEYBORD_M               = 0x32,
		KEYBORD_COMMA           = 0x33,
		KEYBORD_PERIOD          = 0x34,    /* . on main keyboard */
		KEYBORD_SLASH           = 0x35,    /* / on main keyboard */
		KEYBORD_RSHIFT          = 0x36,
		KEYBORD_MULTIPLY        = 0x37,    /* * on numeric keypad */
		KEYBORD_LMENU           = 0x38,    /* left Alt */
		KEYBORD_SPACE           = 0x39,
		KEYBORD_CAPITAL         = 0x3A,
		KEYBORD_F1              = 0x3B,
		KEYBORD_F2              = 0x3C,
		KEYBORD_F3              = 0x3D,
		KEYBORD_F4              = 0x3E,
		KEYBORD_F5              = 0x3F,
		KEYBORD_F6              = 0x40,
		KEYBORD_F7              = 0x41,
		KEYBORD_F8              = 0x42,
		KEYBORD_F9              = 0x43,
		KEYBORD_F10             = 0x44,
		KEYBORD_NUMLOCK         = 0x45,
		KEYBORD_SCROLL          = 0x46,    /* Scroll Lock */
		KEYBORD_NUMPAD7         = 0x47,
		KEYBORD_NUMPAD8         = 0x48,
		KEYBORD_NUMPAD9         = 0x49,
		KEYBORD_SUBTRACT        = 0x4A,    /* - on numeric keypad */
		KEYBORD_NUMPAD4         = 0x4B,
		KEYBORD_NUMPAD5         = 0x4C,
		KEYBORD_NUMPAD6         = 0x4D,
		KEYBORD_ADD             = 0x4E,    /* + on numeric keypad */
		KEYBORD_NUMPAD1         = 0x4F,
		KEYBORD_NUMPAD2         = 0x50,
		KEYBORD_NUMPAD3         = 0x51,
		KEYBORD_NUMPAD0         = 0x52,
		KEYBORD_DECIMAL         = 0x53,    /* . on numeric keypad */
		KEYBORD_OEM_102         = 0x56,    /* <> or \| on RT 102-key keyboard (Non-U.S.) */
		KEYBORD_F11             = 0x57,
		KEYBORD_F12             = 0x58,
		KEYBORD_F13             = 0x64,    /*                     (NEC PC98) */
		KEYBORD_F14             = 0x65,    /*                     (NEC PC98) */
		KEYBORD_F15             = 0x66,    /*                     (NEC PC98) */
		KEYBORD_KANA            = 0x70,    /* (Japanese keyboard)            */
		KEYBORD_ABNT_C1         = 0x73,    /* /? on Brazilian keyboard */
		KEYBORD_CONVERT         = 0x79,    /* (Japanese keyboard)            */
		KEYBORD_NOCONVERT       = 0x7B,    /* (Japanese keyboard)            */
		KEYBORD_YEN             = 0x7D,    /* (Japanese keyboard)            */
		KEYBORD_ABNT_C2         = 0x7E,    /* Numpad . on Brazilian keyboard */
		KEYBORD_NUMPADEQUALS    = 0x8D,    /* = on numeric keypad (NEC PC98) */
		KEYBORD_PREVTRACK       = 0x90,    /* Previous Track (DIK_CIRCUMFLEX on Japanese keyboard) */
		KEYBORD_AT              = 0x91,    /*                     (NEC PC98) */
		KEYBORD_COLON           = 0x92,    /*                     (NEC PC98) */
		KEYBORD_UNDERLINE       = 0x93,    /*                     (NEC PC98) */
		KEYBORD_KANJI           = 0x94,    /* (Japanese keyboard)            */
		KEYBORD_STOP            = 0x95,    /*                     (NEC PC98) */
		KEYBORD_AX              = 0x96,    /*                     (Japan AX) */
		KEYBORD_UNLABELED       = 0x97,    /*                        (J3100) */
		KEYBORD_NEXTTRACK       = 0x99,    /* Next Track */
		KEYBORD_NUMPADENTER     = 0x9C,    /* Enter on numeric keypad */
		KEYBORD_RCONTROL        = 0x9D,
		KEYBORD_MUTE            = 0xA0,    /* Mute */
		KEYBORD_CALCULATOR      = 0xA1,    /* Calculator */
		KEYBORD_PLAYPAUSE       = 0xA2,    /* Play / Pause */
		KEYBORD_MEDIASTOP       = 0xA4,    /* Media Stop */
		KEYBORD_VOLUMEDOWN      = 0xAE,    /* Volume - */
		KEYBORD_VOLUMEUP        = 0xB0,    /* Volume + */
		KEYBORD_WEBHOME         = 0xB2,    /* Web home */
		KEYBORD_NUMPADCOMMA     = 0xB3,    /* , on numeric keypad (NEC PC98) */
		KEYBORD_DIVIDE          = 0xB5,    /* / on numeric keypad */
		KEYBORD_SYSRQ           = 0xB7,
		KEYBORD_RMENU           = 0xB8,    /* right Alt */
		KEYBORD_PAUSE           = 0xC5,    /* Pause */
		KEYBORD_HOME            = 0xC7,    /* Home on arrow keypad */
		KEYBORD_UP              = 0xC8,    /* UpArrow on arrow keypad */
		KEYBORD_PRIOR           = 0xC9,    /* PgUp on arrow keypad */
		KEYBORD_LEFT            = 0xCB,    /* LeftArrow on arrow keypad */
		KEYBORD_RIGHT           = 0xCD,    /* RightArrow on arrow keypad */
		KEYBORD_END             = 0xCF,    /* End on arrow keypad */
		KEYBORD_DOWN            = 0xD0,    /* DownArrow on arrow keypad */
		KEYBORD_NEXT            = 0xD1,    /* PgDn on arrow keypad */
		KEYBORD_INSERT          = 0xD2,    /* Insert on arrow keypad */
		KEYBORD_DELETE          = 0xD3,    /* Delete on arrow keypad */
		KEYBORD_LWIN            = 0xDB,    /* Left Windows key */
		KEYBORD_RWIN            = 0xDC,    /* Right Windows key */
		KEYBORD_APPS            = 0xDD,    /* AppMenu key */
		KEYBORD_POWER           = 0xDE,    /* System Power */
		KEYBORD_SLEEP           = 0xDF,    /* System Sleep */
		KEYBORD_WAKE            = 0xE3,    /* System Wake */
		KEYBORD_WEBSEARCH       = 0xE5,    /* Web Search */
		KEYBORD_WEBFAVORITES    = 0xE6,    /* Web Favorites */
		KEYBORD_WEBREFRESH      = 0xE7,    /* Web Refresh */
		KEYBORD_WEBSTOP         = 0xE8,    /* Web Stop */
		KEYBORD_WEBFORWARD      = 0xE9,    /* Web Forward */
		KEYBORD_WEBBACK         = 0xEA,    /* Web Back */
		KEYBORD_MYCOMPUTER      = 0xEB,    /* My Computer */
		KEYBORD_MAIL            = 0xEC,    /* Mail */
		KEYBORD_MEDIASELECT     = 0xED     /* Media Select */
	};
}
#endif // !KEY_BORD_KEY_TYPE_H_