#ifndef HAS_GET_UPDATE_PRIORITY_CHECKER_H_
#define HAS_GET_UPDATE_PRIORITY_CHECKER_H_

#include "../HasFuncCheckMacro.h"
HAS_FUNC_CHECK(getUpdatePriority)

#endif // !HAS_GET_UPDATE_PRIORITY_CHECKER_H_