#ifndef HAS_GET_COLLISION_GROUP_CHECKER_H_
#define HAS_GET_COLLISION_GROUP_CHECKER_H_

#include "../HasFuncCheckMacro.h"
HAS_FUNC_CHECK(getCollisionGroup)

#endif // !HAS_GET_COLLISION_GROUP_CHECKER_H_