#ifndef HAS_SET_PROCESSING_CLASS_PTR_CHECKER_H_
#define HAS_SET_PROCESSING_CLASS_PTR_CHECKER_H_

#include "../HasFuncCheckMacro.h"
HAS_FUNC_CHECK(setProcessingClassPtr)

#endif // !HAS_SET_PROCESSING_CLASS_PTR_CHECKER_H_
