#ifndef KEY_BORD_KEY_TYPE_H_
#define KEY_BORD_KEY_TYPE_H_

namespace tktk
{
	enum class KeybordKeyType
	{
		key_Escape			= 0x01,
		key_1				= 0x02,
		key_2				= 0x03,
		key_3				= 0x04,
		key_4				= 0x05,
		key_5				= 0x06,
		key_6				= 0x07,
		key_7				= 0x08,
		key_8				= 0x09,
		key_9				= 0x0A,
		key_0				= 0x0B,
		key_Minus			= 0x0C,    /* - on main keyboard */
		key_Equals			= 0x0D,
		key_Back			= 0x0E,    /* backspace */
		key_Tab				= 0x0F,
		key_Q				= 0x10,
		key_W				= 0x11,
		key_E				= 0x12,
		key_R				= 0x13,
		key_T				= 0x14,
		key_Y				= 0x15,
		key_U				= 0x16,
		key_I				= 0x17,
		key_O				= 0x18,
		key_P				= 0x19,
		key_Lbracket		= 0x1A,
		key_Rbracket		= 0x1B,
		key_Return			= 0x1C,    /* Enter on main keyboard */
		key_Lcontrol		= 0x1D,
		key_A				= 0x1E,
		key_S				= 0x1F,
		key_D				= 0x20,
		key_F				= 0x21,
		key_G				= 0x22,
		key_H				= 0x23,
		key_J				= 0x24,
		key_K				= 0x25,
		key_L				= 0x26,
		key_Semicolon		= 0x27,
		key_Apostrophe		= 0x28,
		key_Grave			= 0x29,    /* accent grave */
		key_Lshift			= 0x2A,
		key_Backslash		= 0x2B,
		key_Z				= 0x2C,
		key_X				= 0x2D,
		key_C				= 0x2E,
		key_V				= 0x2F,
		key_B				= 0x30,
		key_N				= 0x31,
		key_M				= 0x32,
		key_Comma			= 0x33,
		key_Period			= 0x34,    /* . on main keyboard */
		key_Slash			= 0x35,    /* / on main keyboard */
		key_Rshift			= 0x36,
		key_Multiply		= 0x37,    /* * on numeric keypad */
		key_Lmenu			= 0x38,    /* left Alt */
		key_Space			= 0x39,
		key_Capital			= 0x3A,
		key_F1				= 0x3B,
		key_F2				= 0x3C,
		key_F3				= 0x3D,
		key_F4				= 0x3E,
		key_F5				= 0x3F,
		key_F6				= 0x40,
		key_F7				= 0x41,
		key_F8				= 0x42,
		key_F9				= 0x43,
		key_F10				= 0x44,
		key_Numlock			= 0x45,
		key_Scroll			= 0x46,    /* Scroll Lock */
		key_Numpad7			= 0x47,
		key_Numpad8			= 0x48,
		key_Numpad9			= 0x49,
		key_SUBTRACT		= 0x4A,    /* - on numeric keypad */
		key_Numpad4			= 0x4B,
		key_Numpad5			= 0x4C,
		key_Numpad6			= 0x4D,
		key_Add				= 0x4E,    /* + on numeric keypad */
		key_Numpad1			= 0x4F,
		key_Numpad2			= 0x50,
		key_Numpad3			= 0x51,
		key_Numpad0			= 0x52,
		key_Decimal			= 0x53,    /* . on numeric keypad */
		key_Oem_102			= 0x56,    /* <> or \| on RT 102-key keyboard (Non-U.S.) */
		key_F11				= 0x57,
		key_F12				= 0x58,
		key_F13				= 0x64,    /*                     (NEC PC98) */
		key_F14				= 0x65,    /*                     (NEC PC98) */
		key_F15				= 0x66,    /*                     (NEC PC98) */
		key_Kana			= 0x70,    /* (Japanese keyboard)            */
		key_Abnt_C1			= 0x73,    /* /? on Brazilian keyboard */
		key_Convert			= 0x79,    /* (Japanese keyboard)            */
		key_Noconvert		= 0x7B,    /* (Japanese keyboard)            */
		key_Yen				= 0x7D,    /* (Japanese keyboard)            */
		key_Abnt_C2			= 0x7E,    /* Numpad . on Brazilian keyboard */
		key_Numpadequals	= 0x8D,    /* = on numeric keypad (NEC PC98) */
		key_Prevtrack		= 0x90,    /* Previous Track (DIK_CIRCUMFLEX on Japanese keyboard) */
		key_At				= 0x91,    /*                     (NEC PC98) */
		key_Colon			= 0x92,    /*                     (NEC PC98) */
		key_Underline		= 0x93,    /*                     (NEC PC98) */
		key_Kanji			= 0x94,    /* (Japanese keyboard)            */
		key_Stop			= 0x95,    /*                     (NEC PC98) */
		key_Ax				= 0x96,    /*                     (Japan AX) */
		key_Unlabeled		= 0x97,    /*                        (J3100) */
		key_Nexttrack		= 0x99,    /* Next Track */
		key_Numpadenter		= 0x9C,    /* Enter on numeric keypad */
		key_Rcontrol		= 0x9D,
		key_Mute			= 0xA0,    /* Mute */
		key_Calculator		= 0xA1,    /* Calculator */
		key_Playpause		= 0xA2,    /* Play / Pause */
		key_Mediastop		= 0xA4,    /* Media Stop */
		key_Volumedown		= 0xAE,    /* Volume - */
		key_Volumeup		= 0xB0,    /* Volume + */
		key_Webhome			= 0xB2,    /* Web home */
		key_Numpadcomma		= 0xB3,    /* , on numeric keypad (NEC PC98) */
		key_Divide			= 0xB5,    /* / on numeric keypad */
		key_Sysrq			= 0xB7,
		key_Rmenu			= 0xB8,    /* right Alt */
		key_Pause			= 0xC5,    /* Pause */
		key_Home			= 0xC7,    /* Home on arrow keypad */
		key_Up				= 0xC8,    /* UpArrow on arrow keypad */
		key_Prior			= 0xC9,    /* PgUp on arrow keypad */
		key_Left			= 0xCB,    /* LeftArrow on arrow keypad */
		key_Right			= 0xCD,    /* RightArrow on arrow keypad */
		key_End				= 0xCF,    /* End on arrow keypad */
		key_Down			= 0xD0,    /* DownArrow on arrow keypad */
		key_Next			= 0xD1,    /* PgDn on arrow keypad */
		key_Insert			= 0xD2,    /* Insert on arrow keypad */
		key_Delete			= 0xD3,    /* Delete on arrow keypad */
		key_Lwin			= 0xDB,    /* Left Windows key */
		key_Rwin			= 0xDC,    /* Right Windows key */
		key_Apps			= 0xDD,    /* AppMenu key */
		key_Power			= 0xDE,    /* System Power */
		key_Sleep			= 0xDF,    /* System Sleep */
		key_Wake			= 0xE3,    /* System Wake */
		key_Websearch		= 0xE5,    /* Web Search */
		key_Webfavorites	= 0xE6,    /* Web Favorites */
		key_Webrefresh		= 0xE7,    /* Web Refresh */
		key_Webstop			= 0xE8,    /* Web Stop */
		key_Webforward		= 0xE9,    /* Web Forward */
		key_Webback			= 0xEA,    /* Web Back */
		key_Mycomputer		= 0xEB,    /* My Computer */
		key_Mail			= 0xEC,    /* Mail */
		key_Mediaselect		= 0xED     /* Media Select */
	};
}
#endif // !KEY_BORD_KEY_TYPE_H_