#pragma once

enum Texture2DId
{
	TEXTURE_2D_SPRITE_TEST = 1,

	TEXTURE_2D_SPRITE_MeSm	= 11,
	TEXTURE_2D_SPRITE_NORM	= 12,
	TEXTURE_2D_SPRITE_AmOc	= 13,
	TEXTURE_2D_SPRITE_CUBE	= 14,
	TEXTURE_2D_SPRITE_ENV	= 15
};