#pragma once

#include <TktkMath.h>
#include <TktkTextProcessing.h>
#include <TktkComponentFramework.h>
#include <TktkAppendComponent.h>
#include <TktkAppend2DComponent.h>
#include <TktkAppend3DComponent.h>
#include "Utility/Enum/SoundId.h"
#include "Utility/Enum/Texture2DId.h"
#include "Utility/Enum/CameraId.h"
#include "Utility/Enum/MaterialId.h"
#include "Utility/Enum/SkeletonId.h"
#include "Utility/Enum/AnimationId.h"
#include "Utility/Enum/MeshId.h"
//#include "Utility/Enum/RenderTargetId.h"
//#include "Utility/Enum/CollisionGroup.h"
//#include "Utility/Enum/ShadowMapId.h"
//#include "Utility/Param/DrawPriority.h"