#ifndef SYSTEM_VERTEX_SHADER_ID_H_
#define SYSTEM_VERTEX_SHADER_ID_H_

namespace tktk
{
	enum SystemVertexShaderId
	{
		SYSTEM_VERTEX_SHADER_SPRITE = -100,
		SYSTEM_VERTEX_SHADER_MESH = -200,
		SYSTEM_VERTEX_SHADER_PBR_MESH = -300,
		SYSTEM_VERTEX_SHADER_IBL_MESH = -400,
		SYSTEM_VERTEX_SHADER_PBR_IBL_MESH = -500,
	};
}
#endif // !SYSTEM_VERTEX_SHADER_ID_H_
