#ifndef SYSTEM_CONSTANT_BUFFER_ID_H_
#define SYSTEM_CONSTANT_BUFFER_ID_H_

namespace tktk
{
	enum SystemConstantBufferId
	{
		SYSTEM_CONSTANT_BUFFER_SPRITE	= -100,
		SYSTEM_CONSTANT_BUFFER_MESH		= -200,
		SYSTEM_CONSTANT_BUFFER_PBR_MESH = -300,
	};
}
#endif // !SYSTEM_CONSTANT_BUFFER_ID_H_