#ifndef SYSTEM_PIXEL_SHADER_ID_H_
#define SYSTEM_PIXEL_SHADER_ID_H_

namespace tktk
{
	enum SystemPixelShaderId
	{
		SYSTEM_PIXEL_SHADER_SPRITE = -100,
		SYSTEM_PIXEL_SHADER_MESH = -200,
		SYSTEM_PIXEL_SHADER_PBR_MESH = -300,
		SYSTEM_PIXEL_SHADER_IBL_MESH = -400,
		SYSTEM_PIXEL_SHADER_PBR_IBL_MESH = -500,
	};
}
#endif // !SYSTEM_PIXEL_SHADER_ID_H_