#ifndef GAME_PAD_NUMBER_H_
#define GAME_PAD_NUMBER_H_

namespace tktk
{
	// ゲームパッドの番号
	enum GamePadNumber
	{
		GAME_PAD_NUMBER_1 = 1,
		GAME_PAD_NUMBER_2 = 2,
		GAME_PAD_NUMBER_3 = 3,
		GAME_PAD_NUMBER_4 = 4,
		GAME_PAD_NUMBER_5 = 5,
		GAME_PAD_NUMBER_6 = 6,
		GAME_PAD_NUMBER_7 = 7,
		GAME_PAD_NUMBER_8 = 8,
		GAME_PAD_NUMBER_9 = 9,
		GAME_PAD_NUMBER_10 = 10,
		GAME_PAD_NUMBER_11 = 11,
		GAME_PAD_NUMBER_12 = 12,
		GAME_PAD_NUMBER_13 = 13,
		GAME_PAD_NUMBER_14 = 14,
		GAME_PAD_NUMBER_15 = 15,
		GAME_PAD_NUMBER_16 = 16,
	};
}
#endif // !GAME_PAD_NUMBER_H_