#ifndef GAME_PAD_BUTTON_TYPE_H_
#define GAME_PAD_BUTTON_TYPE_H_

namespace tktk
{
	// マウスのボタンの種類
	enum GamePadButtonType
	{
		GAME_PAD_UP_BUTTON				= (0x0001),
		GAME_PAD_DOWN_BUTTON			= (0x0002),
		GAME_PAD_LEFT_BUTTON			= (0x0004),
		GAME_PAD_RIGHT_BUTTON			= (0x0008),
		GAME_PAD_START_BUTTON			= (0x0010),
		GAME_PAD_BACK_BUTTON			= (0x0020),
		GAME_PAD_LEFT_THUMB_BUTTON		= (0x0040),
		GAME_PAD_RIGHT_THUMB_BUTTON		= (0x0080),
		GAME_PAD_LEFT_SHOULDER_BUTTON	= (0x0100),
		GAME_PAD_RIGHT_SHOULDER_BUTTON	= (0x0200),
		GAME_PAD_A_BUTTON				= (0x0400),
		GAME_PAD_B_BUTTON				= (0x0800),
		GAME_PAD_X_BUTTON				= (0x1000),
		GAME_PAD_Y_BUTTON				= (0x2000)
	};
}

#endif // !GAME_PAD_BUTTON_TYPE_H_